### ISSUE TITLE
Backend Todo 정리

### ISSUE THREAD

**Issue by dooking** [boostcamp-2020/Project15-C-Client-Based-Formula-Editor#69]
## Todo
- [x] Alias 설정
- [x] 나머지 CRD 완성 -> typeORM 문법 위키 정리
- [x] oAuth 소셜로그인 구현
- [x] HTTP Status Code 상수화
- [x] 에러 상수화
